version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"
