name: tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.4
        poetry_version: 1.0.10
        working_directory: .
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.4
        poetry_version: 1.0.10
        working_directory: .
        args: run python -m pytest --cov=app --cov-branch --cov-fail-under=50 tests/
